---
title: "Case2_Case_Study_Road_Map"
author: "Luis Rincones"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

# Case Study 2: How Can a Wellness Technology Company Play It Smart?<br>

This document will describe the work done using the google analytics process.
**APPASA**  (Ask, Prepare, Process, Analyze, Share and Act)


## ASK<br>
The first phase of the APPASA is Ask<br>

The problem I am trying to solve:<br>
**Analyze smart device data to gain insight into how consumers are using their smart devices**<br>

Select one Bellabeat product to apply these insights to in my presentation<br>
**Bellabeat membership**<br>

Discovering how the data from the other products can be used in the Bellabeat membership 
to enhance its value for the members<br> 


**Stakeholders**<br>
* Urška Sršen: Bellabeat’s cofounder and Chief Creative Officer<br>

* Sando Mur: Mathematician and Bellabeat’s cofounder; key member of the Bellabeat executive team<br>

* Bellabeat marketing analytics team<br>

* Bellabeat executive team<br>

**Deliverable**<br>
* Analyze the available data to discover how smart devices are used<br>
* Extract from the Data information related to Bellabeat's products<br>
1.  Seek information that add value to the actual funcionality<br>
2.  How do products could complement other products?<br>

Questions to guide the analysis:<br>
1. What are some trends in smart device usage?<br>
2. How could these trends apply to Bellabeat customers?<br>
3. How could these trends help influence Bellabeat marketing strategy?<br>
\newpage

## Prepare <br>

**Guiding questions**<br> 
* Where is your data stored?<br>
I stored the data in the project folder in Rstudio in my computer<br>
Names as in the source, however for the dataframes, I used the first parte before the "_merged.csv"
<br>
The data is sourced  from [Kaggle](https://www.kaggle.com/arashnic/fitbit)
These datasets were generated by respondents to a distributed survey between 03.12.2016 - 05.12.2016<br> 
Thirty eligible Fitbit users consented to the submission of personal tracker data<br>
<br>
* How is the data organized?<br>
Eighteen files, three of them in two formats(wide and narrow)<br>
For analysis I wull use fifteen files<br>
* dailyActivity<br>
* dailyCalories<br>
* dailyIntensities<br>
* dailySteps<br>
* hourlyCalories<br>
* hourlyIntensities<br>
* hourlySteps<br>
* minuteCaloriesNarrow<br>
* minuteIntensitiesNarrow<br>
* minuteStepsNarrow<br>
* minuteMETsNarrow<br>
* minuteSleep<br>
* heartrate<br>
* sleepday<br>
* weightLogInfo<br>
 

Determine what to use for the analysis<br>
We have files that register the action generating activity, *steps* the steps have different *intensities* 
* dailySteps<br>
* hourlySteps<br>
* minuteStepsNarrow<br>
* dailyIntensities<br>
* hourlyIntensities<br>
* minuteIntensitiesNarrow<br>


The activity reflected in the human body, is measured by *Calories* and *METs* 
* dailyCalories<br>
* hourlyCalories<br>
* minuteCaloriesNarrow<br>
* minuteMETsNarrow<br>

Other Human body measures we have<br>
* heartrate<br>
* sleepday<br>
* minuteSleep<br>
* weightLogInfo<br>


This is the main file I will use<br>
The file that summarizes the activities by day and Id
* **dailyActivity**<br>

Indicates distance in 4 levels<br>
* VeryActive<br>
* ModeratelyActive<br>
* LightActive<br>
* SedentaryActive<br>

Indicates the minutes in each activity level in 4 levels<br>
* VeryActiveMinutes<br>
* FairlyActiveMinutes<br>
* LightlyActiveMinutes<br>
* SedentaryMinutes<br>

The last variable is *Calories*<br>

This file is the main file to use for the analysis. 
The sum of the minutes do not add to a day 1440 minutes for all the Ids. 462 records do not add to a full day and 478 that do<br>

The correlation between steps and calories is stronger for the records with full day<br> 
I will use those records for the initial analysis<br>



* Is it in long or wide format?<br>
* Are there issues with bias or credibility in this data?<br>
  The bias expected when humans logged data, the data captured automatically is not bias<br>
  some data had fewer persons than the rest "weightlogInfo"and "heartrate" in order to use them more data is required.
* Does your data *ROCCC*?<br>
* Reliable --> with the constraints of Crowdsourcing 
* Original --> The files I am using are stored in Kaggle
* Comprehensive --> All the data that was contracted
* Current --> Updated every year last update 2020-12-16
* Cited --> 4972 downloads 

For the dailyActivity file. The sum of the minutes do not add to a day 1440 minutes for all the Ids. 462 records do not add to a full day and 478 that do<br>

The correlation between steps and calories is stronger for the records with full day<br> 
I will use the records that add for a full day<br>

* How are you addressing licensing, privacy, security, and accessibility?<br>
Those concerns were addresed in by the source the license is CCO: Public Domain<br>
The data is anonymized.    
* How did you verify the data’s integrity?<br>
For the main file I plan to use dailyactivity, I checked the sum of the minutes add to a full day, will use only the records that represent a full day.
* How does it help you answer your question?<br>
The question as related to the Bellabeat membership can be answered with the aggregated information in dailyActivity.  
* Are there any problems with the data?<br>
As indicated in the Integrity 

\newpage

## Process<br>
**Guiding questions**<br> 
*What tools are you choosing and why?* <br>
Rstudio for its flexibility and plotting capabilities, I may generate a notebook to publish in Kaggle<br>

*Have you ensured your data’s integrity?*<br>
I made a summary of the files with unique users Id and number of records, another summary for file, their fields and data types(df_st) <br>
Reviewed the number of records some files have too few records that may not use<br>
Reviewed the number of unique Ids for minuteSleep vs sleepDay<br>
Will use the sleepDay data set, as the main source for the analysis <br>



*What steps have you taken to ensure that your data is clean?*<br> 
Reviewed the data and the data types in the different files<br>
For the dailyActivity file. I checked that the data in minutes reflected the whole day<br>
* will prepare a subset where the sum of the minutes is 1440.

*How can you verify that your data is clean and ready to analyze?*<br> 
I did some preanalysis to verify the data was workable, the partial units of time added to the day data, based on that decided to use the summarized data in dailyActivity

*Have you documented your cleaning process so you can review and share those results?*<br>
A rmd file for the process work with the key tasks.<br>
**Key tasks**<br>
1. Check the data for errors<br> 
2. Choose your tools<br>
3. Transform the data so you can work with it effectively<br> 
4. Document the cleaning process<br>.

**Deliverable**<br> 
* An rmd file with the code and the dataframes to be used in the Analyze phase<br>

\newpage

## Analyze<br>






